'use client';
import {useState,useEffect,useMemo,useCallback,useRef} from 'react';
import dynamic from 'next/dynamic';
import {MotionConfig} from 'framer-motion';
import {ArrowUpRight} from 'lucide-react';
import {Product,filterProducts,WHATSAPP_NUMBER,whatsapp} from '@/lib/catalog';
import {Navbar,CatalogHeader,SearchBar,CategoryFilter,PriceFilter,SortControl} from './Controls';
import {ProductGrid} from './ProductGrid';
import HeroSection from './hero/HeroSection';
import DocumentationGallery from './DocumentationGallery';
const ProductModal=dynamic(()=>import('./ProductModal'));
const WishlistDrawer=dynamic(()=>import('./WishlistDrawer'));
const STORAGE='kembang-panwis:pilihanmu:v1';
export default function Catalog({products}:{products:Product[]}) {
 const [query,setQuery]=useState('');const [category,setCategory]=useState('Semua');const [price,setPrice]=useState('all');const [sort,setSort]=useState('default');
 const [saved,setSaved]=useState<string[]>([]);const [active,setActive]=useState<Product|null>(null);const [wishlist,setWishlist]=useState(false);const [scrolled,setScrolled]=useState(false);const [toast,setToast]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=useCallback((message:string)=>{setToast(message);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),5000);},[]);
 useEffect(()=>{return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{function read(){try{const data=JSON.parse(localStorage.getItem(STORAGE)||'[]');setSaved(Array.isArray(data)?Array.from(new Set(data.filter((v:unknown):v is string=>typeof v==='string'&&products.some(p=>p.id===v)))):[]);}catch{notify('Pilihanmu tidak dapat dibaca. Kamu tetap bisa menyimpan selama halaman ini terbuka.');}}read();const sync=(e:StorageEvent)=>{if(e.key===STORAGE||e.key===null)read();};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[products,notify]);
 useEffect(()=>{const sync=()=>{const code=new URL(location.href).searchParams.get('product');const p=products.find(p=>p.code===code);setActive(p||null);if(p)setWishlist(false);if(code&&!p)notify('Produk pada tautan tidak ditemukan. Silakan jelajahi koleksi.');};sync();window.addEventListener('popstate',sync);const scroll=()=>setScrolled(window.scrollY>Math.max(12,(document.getElementById('home')?.offsetHeight||0)-95));scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('scroll',scroll);};},[products,notify]);
 function toggle(p:Product){const next=saved.includes(p.id)?saved.filter(id=>id!==p.id):[...saved,p.id];setSaved(next);try{localStorage.setItem(STORAGE,JSON.stringify(next));notify(next.includes(p.id)?'Ditambahkan ke Pilihanmu.':'Dihapus dari Pilihanmu.');}catch{notify('Pilihan tersimpan sementara. Penyimpanan browser tidak tersedia.');}}
 function open(p:Product){setWishlist(false);setActive(p);const u=new URL(location.href);u.searchParams.set('product',p.code);history.pushState(null,'',u);}
 function close(){setActive(null);const u=new URL(location.href);u.searchParams.delete('product');history.replaceState(null,'',u);}
 function reset(){setQuery('');setCategory('Semua');setPrice('all');setSort('default');}
 const filtered=useMemo(()=>filterProducts(products,query,category,price,sort),[products,query,category,price,sort]);const hasFilters=query||category!=='Semua'||price!=='all';
 return <MotionConfig reducedMotion="user"><Navbar scrolled={scrolled} count={saved.length} onWishlist={()=>{close();setWishlist(true);}}/><main><HeroSection/><section id="catalog" className="catalog-transition" tabIndex={-1} aria-label="Katalog produk"><span id="katalog"/><CatalogHeader/><section className="catalog-content" aria-label="Koleksi Kembang Panwis"><SearchBar value={query} onChange={setQuery}/><CategoryFilter value={category} onChange={setCategory}/><div className="catalog-tools"><div className="result-count" role="status"><strong>{filtered.length}</strong> kembang untukmu {hasFilters&&<button onClick={reset}>Reset filter</button>}</div><div className="filter-controls"><PriceFilter value={price} onChange={setPrice}/><SortControl value={sort} onChange={setSort}/></div></div><ProductGrid products={filtered} saved={saved} onSave={toggle} onOpen={open} onReset={reset}/><div className="collection-end"><span/>DIRANGKAI UNTUK MOMEN BERARTI<span/></div></section></section><DocumentationGallery/></main><footer id="kontak"><div><a className="footer-brand" href="#home">KEMBANG PANWIS</a><p>Sebuah kembang. Sejuta rasa bangga.</p></div><div className="footer-contact"><span>UNTUK HARI ISTIMEWAMU</span>{WHATSAPP_NUMBER?<a href={whatsapp()} target="_blank" rel="noopener noreferrer">Hubungi Kembang Panwis <ArrowUpRight size={17}/></a>:<button onClick={()=>notify('Kontak WhatsApp Kembang Panwis segera tersedia.')}>Hubungi Kembang Panwis <ArrowUpRight size={17}/></button>}<small>{WHATSAPP_NUMBER?'Konsultasikan pilihan kembangmu.':'Kontak pemesanan segera tersedia.'}</small></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Kembang Panwis</span><span>Untuk setiap perjalanan yang patut dirayakan.</span></div></footer>{active&&<ProductModal key={active.id} product={active} saved={saved.includes(active.id)} onSave={()=>toggle(active)} onClose={close} notify={notify} message={toast}/>}{wishlist&&<WishlistDrawer products={products.filter(p=>saved.includes(p.id))} onClose={()=>setWishlist(false)} onOpen={open} onRemove={toggle} message={toast}/>}<div className={`toast ${toast?'visible':''}`} role="status" aria-live="polite">{toast}</div></MotionConfig>;
}
