'use client';
import {Search,X,Heart,ArrowUpRight} from 'lucide-react';
import {categories} from '@/lib/catalog';
import {motion} from 'framer-motion';
export function Navbar({count,onWishlist,scrolled}:{count:number;onWishlist:()=>void;scrolled:boolean}) {return <header className={`navbar cinematic-nav ${scrolled?'scrolled':''}`}><a className="brand" href="#home" aria-label="Kembang Panwis, beranda"><span>KEMBANG PANWIS</span><small>FLOWERS FOR YOUR MILESTONES</small></a><nav aria-label="Navigasi utama"><a className="nav-catalog" href="#catalog">Katalog</a><button onClick={onWishlist} className="wishlist-nav"><Heart size={17}/><span>Pilihanmu</span><b>{count}</b></button><a href="#kontak" className="nav-contact">Kontak <ArrowUpRight size={15}/></a></nav></header>;}
export function CatalogHeader(){return <motion.section className="catalog-header" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.55}}><div className="eyebrow"><i/> THE GRADUATION COLLECTION <i/></div><h2>Temukan <em>Kembangmu.</em></h2><p>Pilih rangkaian yang menemani hari istimewamu.</p></motion.section>;}
export function SearchBar({value,onChange}:{value:string;onChange:(s:string)=>void}){return <div className="searchbox"><Search size={19}/><input aria-label="Cari produk" placeholder="Cari kode atau bunga…" value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Hapus pencarian" onClick={()=>onChange('')}><X size={18}/></button>}<span className="search-hint">TEMUKAN YANG BERARTI</span></div>;}
export function CategoryFilter({value,onChange}:{value:string;onChange:(s:string)=>void}){return <div className="categories" aria-label="Kategori produk">{categories.map(c=><button key={c} aria-pressed={value===c} className={value===c?'active':''} onClick={()=>onChange(c)}>{c}</button>)}</div>;}
export function PriceFilter({value,onChange}:{value:string;onChange:(s:string)=>void}){return <label className="select-control"><span>Harga</span><select aria-label="Filter harga" value={value} onChange={e=>onChange(e.target.value)}><option value="all">Semua harga</option><option value="under100">&lt; Rp100 ribu</option><option value="100to200">Rp100–200 ribu</option><option value="200to300">&gt; Rp200–300 ribu</option><option value="over300">&gt; Rp300 ribu</option></select></label>;}
export function SortControl({value,onChange}:{value:string;onChange:(s:string)=>void}){return <label className="select-control"><span>Urutkan</span><select aria-label="Urutkan produk" value={value} onChange={e=>onChange(e.target.value)}><option value="default">Urutan katalog</option><option value="low">Harga terendah</option><option value="high">Harga tertinggi</option></select></label>;}
